apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpt-oss-pvc
  namespace: llm-d-rhaii
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: shared-vast