apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nvme
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: shared-nvme-las1
  volumeMode: Filesystem
