apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-hdd
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  storageClassName: shared-hdd-las1
  volumeMode: Filesystem
